package org.backmeup.index.sharing.policy;

public enum SharingPolicies {

    SHARE_INDEX_DOCUMENT, SHARE_INDEX_DOCUMENT_GROUP, SHARE_BACKUP, SHARE_ALL_AFTER_NOW, SHARE_ALL_INKLUDING_OLD, SHARE_TAGGED_COLLECTION

}
